name: math_riddles
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  material_design_icons_flutter: ^4.0.5045
  day_night_switch: ^0.0.2+1
  shared_preferences: ^0.5.6+3
  cloud_firestore: ^0.13.4+2
  device_info: ^0.4.2+1
  connectivity: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  
  assets:
   - lib/assets/images/Math.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/montserrat/Montserrat-ExtraLightItalic.otf 
          weight: 100
        - asset: lib/assets/fonts/montserrat/Montserrat-Light.otf 
          weight: 200
        - asset: lib/assets/fonts/montserrat/Montserrat-Regular.otf 
          weight: 300
        - asset: lib/assets/fonts/montserrat/Montserrat-Medium.otf 
          weight: 400
        - asset: lib/assets/fonts/montserrat/Montserrat-SemiBold.otf
          weight: 500
        - asset: lib/assets/fonts/montserrat/Montserrat-Bold.otf 
          weight: 600
        - asset: lib/assets/fonts/montserrat/Montserrat-Black.otf 
          weight: 700
        